---
- name: Register Date
  command: date
  register: date_cmd
  when: true

- name: Init block with date
  set_fact:
    b1: "['# Updated at {{ date_cmd.stdout }}', ''] + {{ b1 }}"

- name: Ensure the hosts block exists in /etc/hosts (remote)
  blockinfile:
    dest: /etc/hosts
    block: "{{ b1 | join('\n') }}"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK - HOSTS"
  become: true

- name: Ensure hostname is in /etc/hosts (remote)
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: "127.0.0.1 localhost {{ inventory_hostname }} {{ fqdn }}"
    owner: root
    group: root
    mode: 0644
  become: true
