---

- name: ensure the hosts block exists in /etc/hosts
  become: true
  blockinfile:
    dest: /etc/hosts
    block: "{{ b1 | join('\n') }}"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK - HOSTS"

- name: ensure hostname is in /etc/hosts
  become: true
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 localhost {{ inventory_hostname }} {{ server_fqdn }}'
    owner: root
    group: root
    mode: 0644
