---

- name: ensure the block exists
  become: true
  local_action:
    module: blockinfile
    dest: /etc/hosts
    block: "{{ b1 | join('\n') }}"
    insertafter: EOF
    marker: "# {mark} ANSIBLE MANAGED BLOCK - HOSTS"
  when: is_local_host|bool == true

- debug: var=inventory_hostname
- debug: var=server_fqdn

- local_action:
    module: lineinfile
    dest: /etc/hosts
    regexp: '^127\.0\.0\.1'
    line: '127.0.0.1 {{ inventory_hostname }} {{ server_fqdn }}'
