---
- set_fact:
    incl_type: "local"
  when: ansible_host == 'localhost'

- set_fact:
    b1: []
  run_once: true

- name: Create the block
  set_fact:
    b1: "{{ b1 }} + ['{{ hostvars[ item ].ip_address }} {{ item }} {{ hostvars[ item ].server_fqdn }}']"
  with_items:
    "{{ groups.all }}"
  when: hostvars[ item ].ip_address is defined
  run_once: true

- include_tasks: hosts.{{ incl_type }}.yml
