---

- set_fact:
    incl_type: "local"
  when: is_local_host|bool == true

- debug: var=incl_type

- set_fact:
    b1: []

- name: Create the block
  set_fact:
    b1: "{{ b1 }} + ['{{ hostvars[ item ].ip_address }} {{ item }} {{ hostvars[ item ].server_fqdn }}']"
  with_items:
    "{{ groups.all }}"
  when: hostvars[ item ].ip_address is defined

#- debug: "msg='b1: {{ b1 }}'"

- include: ./hosts.{{ incl_type }}.yml
